---
arch: ppc64le
if: type = pull_request
dist: focal
os: linux
language: shell

services:
    - docker

before_install:
    - docker pull registry.access.redhat.com/ubi8/ubi:8.5

matrix:
    include:
       - name: My repo
         env: personal   
         script:
            - sudo apt-get install jq wget -y
            - echo "Downloading PR $TRAVIS_PULL_REQUEST script!"
            - curl -H "Accept: application/json" -H "Authorization: token $GH_TOKEN" https://api.github.com/repos/anup-kodlekere/travis-bs/pulls/$TRAVIS_PULL_REQUEST/files > /tmp/out.json
            - wget $(jq .[0].raw_url /tmp/out.json | tr -d \")
            - ls $PWD
            - docker run -dt --name test --rm -v $PWD:/home/tester registry.access.redhat.com/ubi8/ubi:8.5 bash -c "/home/tester/script.sh"
            - docker logs -f test
